export type GetAllProducts = {
  id: number;
  title: string;
  price: number;
  rating: number;
  category: string;
};

const getAllProducts: GetAllProducts[] = [
  {
    id: 1,
    title: 'Perfume Paco Rabanne 1 Million',
    price: 399.9,
    rating: 4.9,
    category: 'fragrances',
  },
  {
    id: 2,
    title: 'Base Líquida Maybelline Fit Me',
    price: 49.9,
    rating: 4.7,
    category: 'beauty',
  },
  {
    id: 3,
    title: 'Sofá Retrátil 3 Lugares Suede',
    price: 1299.9,
    rating: 4.5,
    category: 'furniture',
  },
  {
    id: 4,
    title: 'Cesta de Café da Manhã com Frutas',
    price: 89.9,
    rating: 4.4,
    category: 'groceries',
  },
  {
    id: 5,
    title: 'Quadro Decorativo Abstrato 3 Peças',
    price: 159.9,
    rating: 4.6,
    category: 'home-decoration',
  },
  {
    id: 6,
    title: 'Jogo de Panelas Tramontina',
    price: 399.0,
    rating: 4.8,
    category: 'kitchen-accessories',
  },
  {
    id: 7,
    title: 'Notebook Lenovo Ideapad 3i',
    price: 3299.0,
    rating: 4.7,
    category: 'laptops',
  },
  {
    id: 8,
    title: 'Camisa Social Slim Fit Branca',
    price: 179.9,
    rating: 4.6,
    category: 'mens-shirts',
  },
  {
    id: 9,
    title: 'Tênis Casual Nike Revolution 6',
    price: 299.99,
    rating: 4.7,
    category: 'mens-shoes',
  },
  {
    id: 10,
    title: 'Relógio Masculino Casio G-Shock',
    price: 899.9,
    rating: 4.8,
    category: 'mens-watches',
  },
  {
    id: 11,
    title: 'Capinha de Celular iPhone 14 Pro',
    price: 49.9,
    rating: 4.5,
    category: 'mobile-accessories',
  },
  {
    id: 12,
    title: 'Capacete Moto Pro Tork Atomic',
    price: 199.0,
    rating: 4.5,
    category: 'motorcycle',
  },
  {
    id: 13,
    title: 'Hidratante Neutrogena Hydro Boost',
    price: 59.9,
    rating: 4.6,
    category: 'skin-care',
  },
  {
    id: 14,
    title: 'Smartphone Samsung Galaxy S23',
    price: 4299.0,
    rating: 4.9,
    category: 'smartphones',
  },
  {
    id: 15,
    title: 'Luvas de Academia Adidas',
    price: 89.9,
    rating: 4.4,
    category: 'sports-accessories',
  },
  {
    id: 16,
    title: 'Óculos de Sol Ray-Ban Aviador',
    price: 649.0,
    rating: 4.9,
    category: 'sunglasses',
  },
  {
    id: 17,
    title: 'Tablet Samsung Galaxy Tab S8',
    price: 3699.0,
    rating: 4.7,
    category: 'tablets',
  },
  {
    id: 18,
    title: 'Blusa Canelada Feminina',
    price: 79.9,
    rating: 4.5,
    category: 'tops',
  },
  {
    id: 19,
    title: 'Mini Veículo Elétrico Infantil',
    price: 1399.0,
    rating: 4.3,
    category: 'vehicle',
  },
  {
    id: 20,
    title: 'Bolsa Tote Feminina Couro',
    price: 229.9,
    rating: 4.6,
    category: 'womens-bags',
  },
  {
    id: 21,
    title: 'Vestido Longo Estampado Verão',
    price: 189.9,
    rating: 4.7,
    category: 'womens-dresses',
  },
  {
    id: 22,
    title: 'Colar Dourado Coração Zircônia',
    price: 149.9,
    rating: 4.6,
    category: 'womens-jewellery',
  },
  {
    id: 23,
    title: 'Sandália Salto Alto Vizzano',
    price: 129.9,
    rating: 4.8,
    category: 'womens-shoes',
  },
  {
    id: 24,
    title: 'Relógio Feminino Michael Kors',
    price: 799.0,
    rating: 4.9,
    category: 'womens-watches',
  },
  {
    id: 25,
    title: 'Camisa Polo Tommy Hilfiger',
    price: 349.9,
    rating: 4.8,
    category: 'mens-shirts',
  },
  {
    id: 26,
    title: 'Tênis Adidas Ultraboost 22',
    price: 749.0,
    rating: 4.9,
    category: 'mens-shoes',
  },
  {
    id: 27,
    title: 'Jaqueta Jeans Masculina Levi’s',
    price: 499.9,
    rating: 4.6,
    category: 'mens-shirts',
  },
  {
    id: 28,
    title: 'Relógio Esportivo Garmin Forerunner',
    price: 1299.0,
    rating: 4.9,
    category: 'mens-watches',
  },
  {
    id: 29,
    title: 'Fone Bluetooth Samsung Buds2',
    price: 499.0,
    rating: 4.7,
    category: 'mobile-accessories',
  },
  {
    id: 30,
    title: 'Blush Compacto Ruby Rose',
    price: 24.9,
    rating: 4.4,
    category: 'beauty',
  },
  {
    id: 31,
    title: 'Mesa de Jantar 4 Lugares',
    price: 799.0,
    rating: 4.5,
    category: 'furniture',
  },
  {
    id: 32,
    title: 'Organizador de Talheres Plástico',
    price: 29.9,
    rating: 4.3,
    category: 'kitchen-accessories',
  },
  {
    id: 33,
    title: 'Camiseta Estampada Calvin Klein',
    price: 179.9,
    rating: 4.7,
    category: 'mens-shirts',
  },
  {
    id: 34,
    title: 'Tênis Vans Old Skool Preto',
    price: 349.9,
    rating: 4.8,
    category: 'mens-shoes',
  },
  {
    id: 35,
    title: 'Quadro Floral para Sala',
    price: 119.9,
    rating: 4.6,
    category: 'home-decoration',
  },
];

export default getAllProducts;
